[package]
name = "pf_hackathon_ocpp_server_2023"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.16.1", features = ["full"] }
tokio-tungstenite = "0.16.0"
tokio-native-tls = "0.3.1"
tungstenite = "0.13.0"


